fix(ci): nvm lol

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,7 +25,77 @@ jobs:
                   ref: ${{ github.event.pull_request.head.sha }}
                   # We need to fetch all branches and commits so that Nx affected has a base to compare against.
                   fetch-depth: 0
-            - uses: mansagroup/nrwl-nx-action@v3
+
+            - uses: actions/checkout@v4
+              name: Checkout [Default Branch]
+              if: ${{ github.event_name != 'pull_request' }}
               with:
-                  targets: lint,build,deploy
-                  nxCloud: true
+                  # We need to fetch all branches and commits so that Nx affected has a base to compare against.
+                  fetch-depth: 0
+
+            # Set node/npm/yarn/pnpm versions using setup-node
+            - uses: pnpm/action-setup@v2
+              with:
+                  version: 8
+            - name: Use Node.js 20
+              uses: actions/setup-node@v3
+              with:
+                  node-version: 20
+                  cache: "pnpm"
+
+            - name: Install dependencies
+              run: pnpm install
+
+            - name: Check out the default branch
+              run: git branch --track master origin/master
+
+            - name: Initialize the Nx Cloud distributed CI run and stop agents when the build tasks are done
+              run: pnpm exec nx-cloud start-ci-run --stop-agents-after=build
+
+            - name: Run commands in parallel
+              run: |
+                  pids=()
+                  # list of commands to be run on main has env flag NX_CLOUD_DISTRIBUTED_EXECUTION set to false
+                  NX_CLOUD_DISTRIBUTED_EXECUTION=false pnpm exec nx-cloud record -- pnpm exec nx format:check & pids+=($!)
+
+                  # list of commands to be run on agents
+                  pnpm exec nx affected -t lint,test,build --parallel=3 & 
+                  pids+=($!)
+
+                  # run all commands in parallel and bail if one of them fails
+                  for pid in ${pids[*]}; do
+                    if ! wait $pid; then
+                      exit 1
+                    fi
+                  done
+
+                  exit 0
+
+    agents:
+        name: Agent ${{ matrix.agent }}
+        runs-on: ubuntu-latest
+        strategy:
+            matrix:
+                # Add more agents here as your repository expands
+                agent: [1, 2, 3]
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
+
+            # Set node/npm/yarn/pnpm versions using setup-node
+            - uses: pnpm/action-setup@v2
+              with:
+                  version: 8
+            - name: Use Node.js 20
+              uses: actions/setup-node@v3
+              with:
+                  node-version: 20
+                  cache: "pnpm"
+
+            - name: Install dependencies
+              run: pnpm install
+
+            - name: Start Nx Agent ${{ matrix.agent }}
+              run: npx nx-cloud start-agent
+              env:
+                  NX_AGENT_NAME: ${{ matrix.agent }}
